{"cells":[{"metadata":{"trusted":true},"cell_type":"code","source":"Now let's see what would happen if we did not have write permission (opening only with 'r'):\n\nIn [3]:\ntry:\n    f = open('testfile','r')\n    f.write('Test write this')\nexcept IOError:\n    # This will only check for an IOError exception and then execute this print statement\n    print(\"Error: Could not find file or read data\")\nelse:\n    print(\"Content written successfully\")\n    f.close()\nError: Could not find file or read data\n    \n    \nWe could have also just said except: if we weren't sure what exception would occur. For example:\n\nIn [4]:\ntry:\n    f = open('testfile','r')\n    f.write('Test write this')\nexcept:\n    # This will check for any exception and then execute this print statement\n    print(\"Error: Could not find file or read data\")\nelse:\n    print(\"Content written successfully\")\n    f.close()\nError: Could not find file or read data\nGreat! Now we don't actually need to memorize that list of exception types! Now what if we kept wanting to run code after the exception occurred? This is where finally comes in.\n\n\n\nWe can use this in conjunction with except. Let's see a new example that will take into account a user providing the wrong input:\n\nIn [6]:\ndef askint():\n    try:\n        val = int(input(\"Please enter an integer: \"))\n    except:\n        print(\"Looks like you did not enter an integer!\")\n\n    finally:\n        print(\"Finally, I executed!\")\n    print(val)\nIn [7]:\naskint()\nPlease enter an integer: 5\nFinally, I executed!\n5\nIn [8]:\naskint()\nPlease enter an integer: five\nLooks like you did not enter an integer!\nFinally, I executed!\n---------------------------------------------------------------------------\nUnboundLocalError                         Traceback (most recent call last)\n<ipython-input-8-cc291aa76c10> in <module>()\n----> 1 askint()\n\n<ipython-input-6-c97dd1c75d24> in askint()\n      7     finally:\n      8         print(\"Finally, I executed!\")\n----> 9     print(val)\n\n\nUnboundLocalError: local variable 'val' referenced before assignment\nNotice how we got an error when trying to print val (because it was never properly assigned). Let's remedy this by asking the user and checking to make sure the input type is an integer:\n\nIn [9]:\ndef askint():\n    try:\n        val = int(input(\"Please enter an integer: \"))\n    except:\n        print(\"Looks like you did not enter an integer!\")\n        val = int(input(\"Try again-Please enter an integer: \"))\n    finally:\n        print(\"Finally, I executed!\")\n    print(val)\nIn [10]:\naskint()\nPlease enter an integer: five\nLooks like you did not enter an integer!\nTry again-Please enter an integer: four\nFinally, I executed!\n---------------------------------------------------------------------------\nValueError                                Traceback (most recent call last)\n<ipython-input-9-92b5f751eb01> in askint()\n      2     try:\n----> 3         val = int(input(\"Please enter an integer: \"))\n      4     except:\n\nValueError: invalid literal for int() with base 10: 'five'\n\nDuring handling of the above exception, another exception occurred:\n\nValueError                                Traceback (most recent call last)\n<ipython-input-10-cc291aa76c10> in <module>()\n----> 1 askint()\n\n<ipython-input-9-92b5f751eb01> in askint()\n      4     except:\n      5         print(\"Looks like you did not enter an integer!\")\n----> 6         val = int(input(\"Try again-Please enter an integer: \"))\n      7     finally:\n      8         print(\"Finally, I executed!\")\n\nValueError: invalid literal for int() with base 10: 'four'\nHmmm...that only did one check. How can we continually keep checking? We can use a while loop!\n\nIn [11]:\ndef askint():\n    while True:\n        try:\n            val = int(input(\"Please enter an integer: \"))\n        except:\n            print(\"Looks like you did not enter an integer!\")\n            continue\n        else:\n            print(\"Yep that's an integer!\")\n            break\n        finally:\n            print(\"Finally, I executed!\")\n        print(val)\nIn [12]:\naskint()\nPlease enter an integer: five\nLooks like you did not enter an integer!\nFinally, I executed!\nPlease enter an integer: four\nLooks like you did not enter an integer!\nFinally, I executed!\nPlease enter an integer: 3\nYep that's an integer!\nFinally, I executed!\n\nProblem 1\nHandle the exception thrown by the code below by using try and except blocks.\n\nIn [1]:\nfor i in ['a','b','c']:\n    print(i**2)\n---------------------------------------------------------------------------\nTypeError                                 Traceback (most recent call last)\n<ipython-input-1-c35f41ad7311> in <module>()\n      1 for i in ['a','b','c']:\n----> 2     print(i**2)\n\nTypeError: unsupported operand type(s) for ** or pow(): 'str' and 'int'\n        \n        \n\n\n\n","execution_count":6,"outputs":[{"output_type":"error","ename":"SyntaxError","evalue":"invalid syntax (<ipython-input-6-5b02b5e4d7a6>, line 1)","traceback":["\u001b[0;36m  File \u001b[0;32m\"<ipython-input-6-5b02b5e4d7a6>\"\u001b[0;36m, line \u001b[0;32m1\u001b[0m\n\u001b[0;31m    Object Oriented Programming\u001b[0m\n\u001b[0m                  ^\u001b[0m\n\u001b[0;31mSyntaxError\u001b[0m\u001b[0;31m:\u001b[0m invalid syntax\n"]}]}],"metadata":{"kernelspec":{"name":"python3","display_name":"Python 3","language":"python"},"language_info":{"name":"python","version":"3.6.11","mimetype":"text/x-python","codemirror_mode":{"name":"ipython","version":3},"pygments_lexer":"ipython3","nbconvert_exporter":"python","file_extension":".py"}},"nbformat":4,"nbformat_minor":4}